#s line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'TestS3' do
    pod 'ResearchKit', '~> 1.0'
    pod 'SwiftyRSA', '~> 0.4.0'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SwiftyJSON', '~> 2.4.0'
end

target 'TestS3Tests' do

end

target 'TestS3UITests' do

end

